export const fighters = [
  { rank: 1, name: 'NARKOTIK ATHLETIC', country: 'Russia', flag: 'RU', weight: '70', fights: 5, wins: 4, draws: 1, losses: 0, instagram: 'https://www.instagram.com/crystalhomewarrior' },
  { rank: 2, name: 'RUSLAN BROKER BRAKER', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 3, draws: 1, losses: 0, instagram: 'https://www.instagram.com/rus.lan.812' },
  { rank: 3, name: 'PASHOK PIVO', country: 'Russia', flag: 'RU', weight: '70', fights: 4, wins: 1, draws: 2, losses: 1, instagram: 'https://www.instagram.com/praga_tatulios' },
  { rank: 4, name: 'PITON', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 1, draws: 3, losses: 0, instagram: 'https://www.instagram.com/prvtya11' },
  { rank: 5, name: 'DICH', country: 'Russia', flag: 'RU', weight: '76', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dichnakolkin.comm' },
  { rank: 6, name: 'BRONSON', country: 'Ukraine', flag: 'UA', weight: '90+', fights: 2, wins: 2, draws: 0, losses: 0, instagram: 'https://www.instagram.com/mr.projar' },
  { rank: 7, name: 'RIZA', country: 'Turkey', flag: 'TR', weight: '70', fights: 5, wins: 1, draws: 2, losses: 2 },
  { rank: 8, name: 'VIKING', country: 'Russia', flag: 'RU', weight: '80', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/denisviking_ugc' },
  { rank: 9, name: 'OZAN', country: 'Turkey', flag: 'TR', weight: '85', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/ozanmma' },
  { rank: 10, name: 'ROSTOK BORSKI', country: 'Russia', flag: 'RU', weight: '75', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/ninocolot' },
  { rank: 11, name: 'VALENTIN VARYAG', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/valentin88varyag' },
  { rank: 12, name: 'MAKOR', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/alexmakorin88' },
  { rank: 13, name: 'AMIR', country: 'Russia', flag: 'RU', weight: '70', fights: 3, wins: 1, draws: 1, losses: 1, instagram: 'https://www.instagram.com/imanov_amir_' },
  { rank: 14, name: 'SHARE', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/share88' },
  { rank: 15, name: 'NIKITA RATIBOR', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/nikita_ratibor_firefighter' },
  { rank: 16, name: 'DIMA DD', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/9dima_dd' },
  { rank: 17, name: 'VICTOR BUTI', country: 'England', flag: 'GB', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 18, name: 'IVAN PARSHIKOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 19, name: 'EDIK', country: 'Ukraine', flag: 'UA', weight: '75', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/demenko777' },
  { rank: 20, name: 'ONUR', country: 'Turkey', flag: 'TR', weight: '75', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/onurtekermma' },
  { rank: 21, name: 'THE BULL', country: 'USA', flag: 'US', weight: '85', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/gtacharlie_decca' },
  { rank: 22, name: 'SALAWAT', country: 'Uzbekistan', flag: 'UZ', weight: '90+', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dzhabbarbergenovs' },
  { rank: 23, name: 'DAN ZIGER', country: 'Nigeria', flag: 'NG', weight: '85', fights: 2, wins: 1, draws: 0, losses: 1 },
  { rank: 24, name: 'BIRKIN F9EVIL', country: 'Ukraine', flag: 'UA', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/f9evil' },
  { rank: 25, name: 'POKOLENIE MIKROZAIMOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/pokoleniemikrozaymov' },
];

export const events = [
  {
    id: 'next', status: 'upcoming', number: '—', date: 'DATE TBA', city: 'THAILAND', venue: 'Venue to be announced',
    title: 'NEXT FIGHT NIGHT', card: 'MATCHMAKING IN PROGRESS', link: 'https://t.me/kurnibratokk',
  },
  {
    id: 'phuket-05', status: 'past', number: '05', date: '18 JAN 2026', city: 'PHUKET', venue: 'White Rabbit Beach Club · 16:20',
    title: 'WEED BOXING 5', card: 'WEEKEND BOXING vs TRAPGLADIATOR', link: 'https://t.me/kurnibratokk/162',
    image: 'https://cdn5.telesco.pe/file/HXr_k5JijHq-MGnOiivXCkBZDQnZaVKgDRLHWtndD21ZKH1DJOPAbe18XXrWSrjE4K3ZCBSORbTArUDV_YsX-R0A2azLfLyp6emhs4eufnLjpzD2xhUFaBe4ECh5GpHoQSgLhNtD7JUPpNk1F4Dz40DUm70CTWe0guGZRHgz1fCPAe4Vz9zWetFmJJPGIeFhawRjhpqi3x8zW78WOhiKWb3eLVQYV8jPypynqY-OKAEHdB0aFn-ok7L-dhBzXWJqgxf5CCsO3vSjeJ2gQQbuRdLTa68KTjiChIXL1Xh8kXHxiat3WtNBl_j8qm20ELc5F9Ixo_TkGqoj4pXLKURNFw.jpg',
  },
  {
    id: 'phuket-04', status: 'past', number: '04', date: '22 JUN 2025', city: 'PHUKET', venue: 'KAIF Jungle Club · 17:00',
    title: 'WEED BOXING 4', card: 'STAS vs LEV · RIZA vs MAKOR', link: 'https://t.me/kurnibratokk/100',
    image: 'https://cdn5.telesco.pe/file/r2DCt-tM5BmGP1HbTlm7s0BWRysVgAsVl7FYVx3SxBuWdpLSiU_k6apUhW84Z869gTP88NreyPDUSR_qh9MzQEoe1jKYEDncv2pBiuJR5XGawoJr8-lzyshkmvWA1WBsEC2acfaFkGS_3dTeQ_VOjW0AfkOHhtLO0bhVfkMTSwucqgl7s-XibJEnPjbHK6czHaLSnOOdOhMirU1QnsRsHew5PgvOlyff17PK0wC6O3LRN-NMs__MJbk6Wh3GZcA4pc-icHc6pz_i4s8t8DMb8hA664WXqWEYybtixf6o0SOR2gAblz89rcf-bYt2BbmU7ud812eGVIQnWq7hJBdeTg.jpg',
  },
  {
    id: 'phuket-03', status: 'past', number: '03', date: '23 FEB 2025', city: 'PHUKET', venue: 'KAIF Jungle Club & Spa · 17:00',
    title: 'WEED BOXING 3', card: '14 FIGHTERS · 7 MATCHUPS', link: 'https://t.me/kurnibratokk/34',
    image: 'https://cdn5.telesco.pe/file/I1yxK_WvY1fjQVwOoH92JgtnFEUP6rvuB6rU_XzrbSRcmV_j9-xf0yuBJmFq84Dek8taWZEsWnqt-XhnrYRCUmUMtvQBwEx5rKyF4nEbiXDMi6wAVwaJB4sOjAKIVAmSggNLh2vVliGtK4F8aXn908OPnbX2KoucplCYUgJeeimrv_NTHY-o8xf65_TLcnrTARmbD3pK2tZDwLfESdXZLwGl1RNaud0fWWA5kM_TdXi5o_3wcUMQ_UUNz3X68JKgL0doiKZRdKzN4v1vBTGFQBBkniylA5Dc5i458Uc4C6lRwDugkTVFYwTJstN2wS0kuhJEPeIvL5iWQqVCIyFw4g.jpg',
  },
  {
    id: 'samui-02', status: 'past', number: '02', date: '10 NOV 2024', city: 'KOH SAMUI', venue: 'Sand Yard Beach Bar · 17:00',
    title: 'WEED BOXING 2', card: 'PIVO vs PITON · DICH vs SHARE', link: 'https://t.me/kurnibratokk/21',
    image: 'https://cdn5.telesco.pe/file/rwZ8xBeTWm6LUDZ1fLqD8KyFzYiMP26Rtbxsu5rvn2RXVdrmNKb7hmR5efzik1iv8J9z6Y4OtlnAppTaIm_uq3h0LMr94cR3g78B5aZltwVmUVMUbE3wqgBPG6bRILK5JHyD_l3vWk_7SsEiYWDkwGD3Oxa0e6ELq3V1M8nsY_0rQxtfFF5fGv2T-uhkBsu-JaJ01o6FDV7iMdG6RR9AzKYtIIbqWNwQjiVoABR7z0UXm8EdZYnUiUKdRpxNP5C78iZHcyO0hH0tC-tT8qYuizozjYbW7udQyUVy3FM8LUSq5KPhnCF5F1o8PElAjdJjnobm_OVIRQ3pcWbruaxnJA.jpg',
  },
  {
    id: 'samui-01', status: 'past', number: '01', date: '26 MAY 2024', city: 'KOH SAMUI', venue: 'Sand Yard Beach · 17:00',
    title: 'WEED BOXING 1', card: 'WHERE THE SERIES STARTED', link: 'https://t.me/kurnibratokk/5',
    image: 'https://cdn5.telesco.pe/file/ucQDBVZRQk5pvCzVZlQLrnDZ5UhDGeuCF09EayZM8HkEbgMAmfBflUt_iQ21wb6zbmWE8XAS2_ZdUz3he-9YarnVY9M3DVIFe0Mpd-oAjlLLkZIvajkQkMQ2jMUiJus-EtnM6hYp5UcpRWwdJI_8z5sO38mMKuUEZm_hPv5IDbgKbbSxLQKSWCy4qskyMjpDe4daQno0hWEJodlDzn4JC_Bql98xycCkD66kOCjI-TlHEbn1tOMD_aB2fv1vk4oA2HbuGWNVtXfa-aVmnqZaofSr4_wZLPeX9tGqEVDVWM1NeBjfaY3kXGhxUlQH73EZazg04fazeeXVHImsIUEr-A.jpg',
  },
];

export const copy = {
  en: {
    nav: ['About', 'Events', 'Fighters', 'Merch'], apply: 'Apply to fight', eyebrow: 'Independent fight series · Thailand',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'A ritual before the bell. Three rounds under boxing rules.',
    scroll: 'Explore the series', rounds: ['THE RITUAL', '3 ROUNDS', '3 MINUTES'],
    manifestoTag: 'A different state of competition', manifesto: 'THE RITUAL ENDS AT THE BELL. THEN ONLY BOXING REMAINS.',
    about: 'Weedboxing is an independent fight series born in Thailand. Before the bell, participants complete a cannabis ritual. Once the round starts, the format is clear: three rounds of three minutes under boxing rules.',
    watch: 'Official teaser', teaser: 'Official teaser · Thailand', next: 'Next event', announced: 'Updates coming soon', ticket: 'Follow updates', lineup: 'Fight card', cardTba: 'Date and card to be announced',
    archive: 'Event archive', archiveTitle: 'FIVE EVENTS. ONE EVOLVING FORMAT.', recap: 'Event details', allEvents: 'All events',
    rankTag: 'Official fighter ranking', rankTitle: 'THE OFFICIAL RANKING.', rankSub: 'Updated after every event. Position reflects results, activity and strength of opposition.',
    fighter: 'Fighter', record: 'Record', weight: 'Weight', allFighters: 'Full ranking', champion: 'Smokeweight champion', contenders: 'Next in line', topRanked: 'Top 10', restRoster: 'The rest of the roster', viewProfile: 'Open profile',
    joinTag: 'Applications are open', joinTitle: 'STEP INTO THE SERIES.', joinText: 'We consider experienced athletes from boxing, Muay Thai, MMA and other combat disciplines. Send your record, weight and recent fight footage to our matchmaking team.', joinButton: 'Apply to fight',
    merchTag: 'The identity of the series', merchTitle: 'WEEDBOXING EDITIONS', buy: 'Coming soon',
    investTag: 'Build the next chapter with us', investTitle: 'A FORMAT BUILT TO TRAVEL.', investText: 'We invite strategic partners, venues and investors to develop an international fight entertainment series rooted in Thailand.', investButton: 'Discuss partnership',
    partners: 'Friends of the project', footer: 'From Thailand. Built for a global audience.', rights: '© 2026 WEEDBOXING. ALL RIGHTS RESERVED.',
    pageEvents: 'THE EVENT ARCHIVE.', pageEventsSub: 'Five editions across Koh Samui and Phuket, plus the next announcement.',
    pageFighters: 'FIGHTER RANKING.', pageFightersSub: 'Every athlete who entered the series. Records are updated after each event.',
    search: 'Search a fighter', filter: 'All weights', fights: 'Fights', wins: 'W', draws: 'D', losses: 'L', country: 'Country', profile: 'IG',
  },
  ru: {
    nav: ['О проекте', 'Ивенты', 'Бойцы', 'Мерч'], apply: 'Подать заявку', eyebrow: 'Независимая бойцовская серия · Таиланд',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'Ритуал перед гонгом. Три раунда по правилам бокса.',
    scroll: 'Смотреть проект', rounds: ['РИТУАЛ', '3 РАУНДА', '3 МИНУТЫ'],
    manifestoTag: 'Другой формат соревнования', manifesto: 'РИТУАЛ ЗАКАНЧИВАЕТСЯ С ГОНГОМ. ДАЛЬШЕ — ТОЛЬКО БОКС.',
    about: 'Weedboxing — независимая бойцовская серия, созданная в Таиланде. Перед гонгом участники проходят каннабис-ритуал. После начала раунда формат предельно ясен: три раунда по три минуты по правилам бокса.',
    watch: 'Официальный тизер', teaser: 'Официальный тизер · Таиланд', next: 'Следующий ивент', announced: 'Анонс скоро', ticket: 'Следить за новостями', lineup: 'Кард', cardTba: 'Дата и состав будут объявлены',
    archive: 'Архив событий', archiveTitle: 'ПЯТЬ ИВЕНТОВ. ОДИН РАЗВИВАЮЩИЙСЯ ФОРМАТ.', recap: 'Подробнее', allEvents: 'Все ивенты',
    rankTag: 'Официальный рейтинг бойцов', rankTitle: 'ОФИЦИАЛЬНЫЙ РЕЙТИНГ.', rankSub: 'Обновляется после каждого события. Позиция учитывает результаты, активность и уровень соперников.',
    fighter: 'Боец', record: 'Рекорд', weight: 'Вес', allFighters: 'Весь рейтинг', champion: 'Smokeweight-чемпион', contenders: 'Дышат в спину', topRanked: 'Топ-10', restRoster: 'Остальной ростер', viewProfile: 'Открыть профиль',
    joinTag: 'Прием заявок открыт', joinTitle: 'СТАНЬ ЧАСТЬЮ СЕРИИ.', joinText: 'Мы рассматриваем опытных атлетов из бокса, муай-тай, MMA и других единоборств. Отправь матчмейкерам свой рекорд, вес и видео последних боев.', joinButton: 'Подать заявку',
    merchTag: 'Визуальный код проекта', merchTitle: 'WEEDBOXING EDITIONS', buy: 'Скоро в продаже',
    investTag: 'Создадим следующую главу вместе', investTitle: 'ФОРМАТ, ГОТОВЫЙ К МАСШТАБУ.', investText: 'Приглашаем стратегических партнеров, площадки и инвесторов развивать международную серию бойцовских событий, созданную в Таиланде.', investButton: 'Обсудить партнерство',
    partners: 'Друзья проекта', footer: 'Создано в Таиланде. Для мировой аудитории.', rights: '© 2026 WEEDBOXING. ВСЕ ПРАВА ЗАЩИЩЕНЫ.',
    pageEvents: 'АРХИВ СОБЫТИЙ.', pageEventsSub: 'Пять выпусков на Самуи и Пхукете и место для следующего анонса.',
    pageFighters: 'РЕЙТИНГ БОЙЦОВ.', pageFightersSub: 'Все атлеты, выходившие в серии. Рекорды обновляются после каждого события.',
    search: 'Найти бойца', filter: 'Все веса', fights: 'Бои', wins: 'П', draws: 'Н', losses: 'Пор', country: 'Страна', profile: 'IG',
  },
  th: {
    nav: ['เกี่ยวกับเรา', 'อีเวนต์', 'นักสู้', 'สินค้า'], apply: 'สมัครชก', eyebrow: 'ซีรีส์การต่อสู้อิสระ · ประเทศไทย',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'พิธีก่อนเสียงระฆัง สามยกภายใต้กติกามวยสากล',
    scroll: 'สำรวจโปรเจกต์', rounds: ['พิธี', '3 ยก', '3 นาที'],
    manifestoTag: 'การแข่งขันในรูปแบบใหม่', manifesto: 'พิธีจบเมื่อระฆังดัง จากนั้นเหลือเพียงมวย',
    about: 'Weedboxing คือซีรีส์การต่อสู้อิสระที่กำเนิดในประเทศไทย ผู้เข้าแข่งขันทำพิธีกัญชาก่อนเสียงระฆัง จากนั้นชกสามยก ยกละสามนาทีภายใต้กติกามวยสากล',
    watch: 'ทีเซอร์อย่างเป็นทางการ', teaser: 'ทีเซอร์อย่างเป็นทางการ · ประเทศไทย', next: 'อีเวนต์ถัดไป', announced: 'ประกาศเร็วๆ นี้', ticket: 'ติดตามข่าวสาร', lineup: 'คู่ชก', cardTba: 'วันและคู่ชกจะประกาศภายหลัง',
    archive: 'คลังอีเวนต์', archiveTitle: 'ห้าอีเวนต์ หนึ่งรูปแบบที่พัฒนาไม่หยุด', recap: 'รายละเอียด', allEvents: 'อีเวนต์ทั้งหมด',
    rankTag: 'อันดับนักสู้อย่างเป็นทางการ', rankTitle: 'อันดับอย่างเป็นทางการ', rankSub: 'อัปเดตหลังทุกอีเวนต์ โดยพิจารณาผลงาน ความต่อเนื่อง และระดับคู่ต่อสู้',
    fighter: 'นักสู้', record: 'สถิติ', weight: 'น้ำหนัก', allFighters: 'อันดับทั้งหมด', champion: 'แชมป์ Smokeweight', contenders: 'ผู้ท้าชิง', topRanked: '10 อันดับแรก', restRoster: 'นักสู้คนอื่น', viewProfile: 'เปิดโปรไฟล์',
    joinTag: 'เปิดรับสมัคร', joinTitle: 'เข้าร่วมซีรีส์', joinText: 'เรารับนักกีฬาที่มีประสบการณ์จากมวยสากล มวยไทย MMA และศิลปะการต่อสู้อื่นๆ ส่งสถิติ น้ำหนัก และวิดีโอการชกล่าสุดให้ทีมงาน', joinButton: 'สมัครชก',
    merchTag: 'เอกลักษณ์ของโปรเจกต์', merchTitle: 'WEEDBOXING EDITIONS', buy: 'เร็วๆ นี้',
    investTag: 'สร้างบทต่อไปด้วยกัน', investTitle: 'รูปแบบที่พร้อมเติบโตทั่วโลก', investText: 'เราเชิญพันธมิตร สถานที่ และนักลงทุน ร่วมพัฒนาซีรีส์การต่อสู้ระดับนานาชาติจากประเทศไทย', investButton: 'พูดคุยความร่วมมือ',
    partners: 'เพื่อนของโปรเจกต์', footer: 'สร้างในประเทศไทย เพื่อผู้ชมทั่วโลก', rights: '© 2026 WEEDBOXING. ALL RIGHTS RESERVED.',
    pageEvents: 'คลังอีเวนต์', pageEventsSub: 'ห้าอีเวนต์บนเกาะสมุยและภูเก็ต พร้อมพื้นที่สำหรับประกาศครั้งต่อไป',
    pageFighters: 'อันดับนักสู้', pageFightersSub: 'นักกีฬาทุกคนที่เข้าร่วมซีรีส์ อัปเดตสถิติหลังทุกอีเวนต์',
    search: 'ค้นหานักสู้', filter: 'ทุกน้ำหนัก', fights: 'ไฟต์', wins: 'ช', draws: 'ส', losses: 'พ', country: 'ประเทศ', profile: 'IG',
  },
};
