export const fighters = [
  { rank: 1, name: 'NARKOTIK ATHLETIC', country: 'Russia', flag: 'RU', weight: '70', fights: 5, wins: 4, draws: 1, losses: 0, instagram: 'https://www.instagram.com/crystalhomewarrior' },
  { rank: 2, name: 'RUSLAN BROKER BRAKER', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 3, draws: 1, losses: 0, instagram: 'https://www.instagram.com/rus.lan.812' },
  { rank: 3, name: 'PASHOK PIVO', country: 'Russia', flag: 'RU', weight: '70', fights: 4, wins: 1, draws: 2, losses: 1, instagram: 'https://www.instagram.com/praga_tatulios' },
  { rank: 4, name: 'PITON', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 1, draws: 3, losses: 0, instagram: 'https://www.instagram.com/prvtya11' },
  { rank: 5, name: 'DICH', country: 'Russia', flag: 'RU', weight: '76', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dichnakolkin.comm' },
  { rank: 6, name: 'BRONSON', country: 'Ukraine', flag: 'UA', weight: '90+', fights: 2, wins: 2, draws: 0, losses: 0, instagram: 'https://www.instagram.com/mr.projar' },
  { rank: 7, name: 'RIZA', country: 'Turkey', flag: 'TR', weight: '70', fights: 5, wins: 1, draws: 2, losses: 2 },
  { rank: 8, name: 'VIKING', country: 'Russia', flag: 'RU', weight: '80', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/denisviking_ugc' },
  { rank: 9, name: 'OZAN', country: 'Turkey', flag: 'TR', weight: '85', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/ozanmma' },
  { rank: 10, name: 'ROSTOK BORSKI', country: 'Russia', flag: 'RU', weight: '75', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/ninocolot' },
  { rank: 11, name: 'VALENTIN VARYAG', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/valentin88varyag' },
  { rank: 12, name: 'MAKOR', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/alexmakorin88' },
  { rank: 13, name: 'AMIR', country: 'Russia', flag: 'RU', weight: '70', fights: 3, wins: 1, draws: 1, losses: 1, instagram: 'https://www.instagram.com/imanov_amir_' },
  { rank: 14, name: 'SHARE', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/share88' },
  { rank: 15, name: 'NIKITA RATIBOR', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/nikita_ratibor_firefighter' },
  { rank: 16, name: 'DIMA DD', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/9dima_dd' },
  { rank: 17, name: 'VICTOR BUTI', country: 'England', flag: 'GB', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 18, name: 'IVAN PARSHIKOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 19, name: 'EDIK', country: 'Ukraine', flag: 'UA', weight: '75', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/demenko777' },
  { rank: 20, name: 'ONUR', country: 'Turkey', flag: 'TR', weight: '75', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/onurtekermma' },
  { rank: 21, name: 'THE BULL', country: 'USA', flag: 'US', weight: '85', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/gtacharlie_decca' },
  { rank: 22, name: 'SALAWAT', country: 'Uzbekistan', flag: 'UZ', weight: '90+', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dzhabbarbergenovs' },
  { rank: 23, name: 'DAN ZIGER', country: 'Nigeria', flag: 'NG', weight: '85', fights: 2, wins: 1, draws: 0, losses: 1 },
  { rank: 24, name: 'BIRKIN F9EVIL', country: 'Ukraine', flag: 'UA', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/f9evil' },
  { rank: 25, name: 'POKOLENIE MIKROZAIMOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/pokoleniemikrozaymov' },
];

export const events = [
  {
    id: 'phuket-05', status: 'past', number: '05', date: '18 JAN 2026', city: 'PHUKET', venue: 'White Rabbit Beach Club · 16:20',
    title: 'WEED BOXING 5', card: 'WEEKEND BOXING vs TRAPGLADIATOR', fights: ['9 FIGHTS · WEEKEND BOXING vs TRAPGLADIATOR'], source: 'https://t.me/kurnibratokk/162',
    image: 'https://cdn5.telesco.pe/file/HXr_k5JijHq-MGnOiivXCkBZDQnZaVKgDRLHWtndD21ZKH1DJOPAbe18XXrWSrjE4K3ZCBSORbTArUDV_YsX-R0A2azLfLyp6emhs4eufnLjpzD2xhUFaBe4ECh5GpHoQSgLhNtD7JUPpNk1F4Dz40DUm70CTWe0guGZRHgz1fCPAe4Vz9zWetFmJJPGIeFhawRjhpqi3x8zW78WOhiKWb3eLVQYV8jPypynqY-OKAEHdB0aFn-ok7L-dhBzXWJqgxf5CCsO3vSjeJ2gQQbuRdLTa68KTjiChIXL1Xh8kXHxiat3WtNBl_j8qm20ELc5F9Ixo_TkGqoj4pXLKURNFw.jpg',
    gallery: [
      'https://cdn5.telesco.pe/file/mF0LK2oNkbbiBQf7truOQf5FFs0KVYlDZxV5upQUwmWNxbtown5Cfli__0wpsqAQzA13K03d1eJR6S3-f8jIlU-LJO628mRNZRmx1r-aQ0QvNyZOQM5h6r-xgyz2pJHk7QfW0NPk06sOO0VWAaHA2SD8MbiRDVX-Kq3Vts2XjEMLH2Gck-5PKjSNgYLnnyOxSYM8bWt9DDevqvVb27MpV0ptnYrvui5rt19-a9be76cumBt3kdwzF32T2JQ0RuPb7xaWAxPkTt3T2GemqKKmiH7qxoeNkExgVMdR7hxlAD8cWFehOhUvgebGdJliZNiKvfaEb8PovflmqbXAazTkaw',
      'https://cdn5.telesco.pe/file/uI4p-bJhSJkVa1KWH9wGXsoDk7zPhjpV2Uh8TLB_DcFPHaZMA7-Z44Vok351KAq2UqYtKwMacyjIzlZ4iqwRCvrQ_Ko3Tl4xAw54umrqrvSvcfziiYpWgn0Yb-pK-1EXJ8bx3fzlmSLcAb03neZaFi0N9PzuRBVSGw0TCh4H4KKHl2jR3_aBwQGILc1XQvfCK1G7Cgy9SvTdLJ9e4BKiAwCRIudBtRS8nNG4xYwX_HWvA9maiUCNn4tQeaNO1U0zcKlTr-otuOds9mkcFbIGF1ttFupWfiAVr6kW5s8Z3l4L8UuuvwTHL46GkkDKDthqxZnT4V75WEJ1YBnA-N9sXg.jpg',
      'https://cdn5.telesco.pe/file/ARK9vbqI6lxOvUh8i_IqgAo7VpNOHoS-Ad0FJYq5dk25InkKdloXT_QigD5DOv8GyADMQQGbBTdJSMcEbdxfO6pCK_F_F_gLQxV4IDDe5gREud8i-Tn4UoFRtfYHcQ-Gb3zEkjPTur8-wAouvSy41VTjouIJVAUEdhKWxpMD3-Jn1pvgizi0O7FNZsZe3wxrVLBALO0Ncq_ep-duE6OW5giVnV34y_Zt50KcZpmptAlyLsWCrQPxJqK4AUs-bhUno9wNpvUnyS99I_IwVM-G6HNUuWcVwXc3gVTL9ODO3jV4CvBl-1pdCQfdPtyQOS7Rt6MBf3NVlOddME9QfWt03A.jpg',
    ],
  },
  {
    id: 'phuket-04', status: 'past', number: '04', date: '22 JUN 2025', city: 'PHUKET', venue: 'KAIF Jungle Club · 17:00',
    title: 'WEED BOXING 4', card: 'STAS vs LEV · RIZA vs MAKOR', fights: ['STAS vs LEV', 'RIZA vs MAKOR', '8 MATCHUPS TOTAL'], source: 'https://t.me/kurnibratokk/100',
    image: 'https://cdn5.telesco.pe/file/r2DCt-tM5BmGP1HbTlm7s0BWRysVgAsVl7FYVx3SxBuWdpLSiU_k6apUhW84Z869gTP88NreyPDUSR_qh9MzQEoe1jKYEDncv2pBiuJR5XGawoJr8-lzyshkmvWA1WBsEC2acfaFkGS_3dTeQ_VOjW0AfkOHhtLO0bhVfkMTSwucqgl7s-XibJEnPjbHK6czHaLSnOOdOhMirU1QnsRsHew5PgvOlyff17PK0wC6O3LRN-NMs__MJbk6Wh3GZcA4pc-icHc6pz_i4s8t8DMb8hA664WXqWEYybtixf6o0SOR2gAblz89rcf-bYt2BbmU7ud812eGVIQnWq7hJBdeTg.jpg',
    gallery: [
      'https://cdn5.telesco.pe/file/g5nJydg9eGzKNVvGsAKOSvu2pcfAVbJy3D77ZAKq1ckEZGOLo5dFSjIZ9BMDghfd9ohZjT81BeXC_vyW2SsHnoiaZpMy0s3RfmU12vyqtfkDv4pl7YsZ1LetHsbuqNS-mOyTC4o3KAxiramHIpsYlb54-X25u_bN6kOyq-aMzGReLNrHYi9Od2hGdqaxYx9xGcjQ8brBB6UeOXPtNhehGPo6Y8Me9w3N92WkbkCKWWZqwx_EPsaWHAIb1Jcn90QHvN4jUmgk7mrGOfen4v3RFLbnd4cr_j1RSlY5gxOBzK-2zP9pnOY9FHyWzDI8-IxcRySYOWgNjRMRzykh6SZqoQ.jpg',
      'https://cdn5.telesco.pe/file/m2PWTqztZz9exK517U9z6h8JxIb_6Q5OR8jDzbel2JJwIBFD3wHXb_sEPkgxb7rbbv707D_25mxZW3666s5Ixz9yjfqbbDhgl_Q_PFpjHab0NNx_e1KSvwll4lDuVV7-2x2jXFv7Bw2HPqS9nWzT4UdRG8gqCZuAxCpdmAv0T7is_ERqQ3l3dxWvN5pouwzCvV2yEzPQ6U8CsnXzPu2NeDBlI14cK53QKLZPJtsPa0oUA-25MEm0LG79DdEQM2I9EUibBmI-KleE2hHiLRwAVwAFQlmVrQjbOFLDG7iSl69w4WjBVas3bma2vrMglCcxDfRK9h3vXG9XwOoefjuUnQ.jpg',
      'https://cdn5.telesco.pe/file/UsicUfMCzsqETbw-wtuGV19y7Q1ydiEDJlg_8BP-etpGMuf2Sg1oVunivBKQqC4X5dFIHlCYI4MSsWfvTlKrwBxk4T6rpakJ-GfOjoXSaXs8xRsKzo8N4iWwQ6ySlPIAXegYVnGtaS_TrRJQvdtdFuqOqZtQaBqKouJyJaJjo6DvarrGH3aF0r4q3slOFAOFm4Wc8zf47dysaOUIluEY2melzXR0gB4PLU4Bc_Wfh3Mf2OQxjKgM34mUnLGIGAccFuiYuF53dhiAguZi-joPYePLQLIkhw7S2U4Th15InjMHf8gXG1y-v93WyiggHHrMGGpfKYcE5I0Lw9B-4K3AeA.jpg',
    ],
  },
  {
    id: 'phuket-03', status: 'past', number: '03', date: '23 FEB 2025', city: 'PHUKET', venue: 'KAIF Jungle Club & Spa · 17:00',
    title: 'WEED BOXING 3', card: '14 FIGHTERS · 7 MATCHUPS', fights: ['14 FIGHTERS · 7 MATCHUPS'], source: 'https://t.me/kurnibratokk/34',
    image: 'https://cdn5.telesco.pe/file/I1yxK_WvY1fjQVwOoH92JgtnFEUP6rvuB6rU_XzrbSRcmV_j9-xf0yuBJmFq84Dek8taWZEsWnqt-XhnrYRCUmUMtvQBwEx5rKyF4nEbiXDMi6wAVwaJB4sOjAKIVAmSggNLh2vVliGtK4F8aXn908OPnbX2KoucplCYUgJeeimrv_NTHY-o8xf65_TLcnrTARmbD3pK2tZDwLfESdXZLwGl1RNaud0fWWA5kM_TdXi5o_3wcUMQ_UUNz3X68JKgL0doiKZRdKzN4v1vBTGFQBBkniylA5Dc5i458Uc4C6lRwDugkTVFYwTJstN2wS0kuhJEPeIvL5iWQqVCIyFw4g.jpg',
    gallery: [
      'https://cdn5.telesco.pe/file/MQ1WXH5lWo1krk5elHo6TVxr30rY4btDTj4U0y-rJaQGX4wOqwjPC2pU9VcU60asBG2lSUj1dCdNuhlMG_OINjlBShcCOgjMHONyLcjwIfuVjthtj0jK0vWmsPMIHDzDS-kKbzgu_uDqOrNgz6sEUcyZGm-_yq22ZDZ88WB9a_GKJeDzAVhU4e-t65yheIVNF4pyDfhWjxt6gRzWWCWqrcVvQ3B9JW51Pt3Z-zYXvh0qmA9E-QDmRt4W8jBGSlUUUhRC3LTAUR-DzA-PSNUqIXHhBpqI-RZc0YcHsgKpot1kiqqNs6SGlt8nA_s_gwxdT-0Qddmn-oQmUEzS9PDIYA',
      'https://cdn5.telesco.pe/file/XagiIZLXvaOSEH1OjSF9ofVlKzPdICGssLIKrvMx2xGIDZ47xMtuCzMRIFrqyBgDJJVd0LqZaCMeFC5VOnbscOy8BvmERYRcZC9as4_kjII5E0mvTUXPge0G9SxqFJCZE3vNcqV8psXro4O3W8gS_HllLlyAXD0mGvwxTTNbGXQ-us-hmiCJj5M0dvS2zShUlVcJt5w1gyvjayQEqIzJc-8rA3XvsnAy05Be_mmKpjz2CcNefd9ruyGbyr_XEckweUX5qWl8_4KXUL1HEQA0E-2CDMbKtnF1JjSeCx1XD2IAm2nFL1vjPlVGhuryDrb1Iy6woDjKipN9pc3FncBlyQ',
      'https://cdn5.telesco.pe/file/W_8_eYiYSzn4O10BbgNio1GHH2QL7HEEjxi7KCfPVZ6QBGPKBCG64J5UC0V8ksgO27Zdx2L9ipnYX22CX4YILzSxDAZ-wQglp0LZQVRxOgXQgivqbWjn7Ou-GONo0Osr6kVTQayWbLxctP7UZj15D0HFb_B5H9K0St4LjFb7HvL2T5QwwQqzAeGaaizm-b-rWIGt-xYL-A9_mQCkVwZzmRO20xS3POyR2PF6C8c_sMtZfwVLD0h9rDPSTx4AiX0fUmFGaNl7zYxy6MrI8wr-AjRS1Ic9yA0PkMQevAvsqp_usQwJoFdrubls2NLgLNbXU0VESC9wHnzkIrwrrOuOHQ',
    ],
  },
  {
    id: 'samui-02', status: 'past', number: '02', date: '10 NOV 2024', city: 'KOH SAMUI', venue: 'Sand Yard Beach Bar · 17:00',
    title: 'WEED BOXING 2', card: 'PIVO vs PITON · DICH vs SHARE', fights: ['PIVO vs PITON', 'DICH vs SHARE', '7 MATCHUPS TOTAL'], source: 'https://t.me/kurnibratokk/21',
    image: 'https://cdn5.telesco.pe/file/rwZ8xBeTWm6LUDZ1fLqD8KyFzYiMP26Rtbxsu5rvn2RXVdrmNKb7hmR5efzik1iv8J9z6Y4OtlnAppTaIm_uq3h0LMr94cR3g78B5aZltwVmUVMUbE3wqgBPG6bRILK5JHyD_l3vWk_7SsEiYWDkwGD3Oxa0e6ELq3V1M8nsY_0rQxtfFF5fGv2T-uhkBsu-JaJ01o6FDV7iMdG6RR9AzKYtIIbqWNwQjiVoABR7z0UXm8EdZYnUiUKdRpxNP5C78iZHcyO0hH0tC-tT8qYuizozjYbW7udQyUVy3FM8LUSq5KPhnCF5F1o8PElAjdJjnobm_OVIRQ3pcWbruaxnJA.jpg',
    gallery: [
      'https://cdn5.telesco.pe/file/o35vVkFSYsKQP2bvYjESE1HgHk7iJHg9MvENv-cc29K2qYnrC2lBxaXWrtKeHv3-b-nerCa0uOVku9pUisRGGFczzyT4ftUL3B-IkuXwmX8wBHef2TeVt-2kINeK-AQ9OxwDskBbpvtMCjsv2HD_1afX5a0J138ybwR3yrkT7y97alrKfPTnF-Xtm4tnm5-a6RXXKq8m4I9gcn9M7Xk-tFggWYgtURO0SewvOdjWl350fGUbPRuVQ6yVoMRQOiZ82nNg5dDVxnCAqVOUbpGCiGIoJmEepTeaLVs6f9zTwzdwd6yjVX0uuBIf1xoAoC_uCCCUTJJ-xCnX14PI2t_XMQ',
      'https://cdn5.telesco.pe/file/HIKjdScN-oVvMCGx_aEXrwHzKHTaBn5gsenMJl2tzC4cJdBypoR_fKtTi0p2n44qbO2U3OOHpTrgG3FFcWu_DD15AbCkCJJSmlJNXL9U8hfoPGxobun1ABIPymt37IPw03CTVQ1JmBOjFFCk6MJhB8ZO1g_UgzCVeOj1iJdlOkBT5GSfYkx0zkbbMfHDPipB9EK69Qkv_cYt_gVSbdZ4fKi4Mvrqybz2H40QOwzrefy42mH2ezLNTVulGSHmMAyNLIe4qAs4ZWTVLYLstE1pGKr8uAoOClKo_73bZL8L83g-YRZ0JlcQ8Twzt0i7cSJusRBXuDFbdLAswTuSZdLYpA',
    ],
  },
  {
    id: 'samui-01', status: 'past', number: '01', date: '26 MAY 2024', city: 'KOH SAMUI', venue: 'Sand Yard Beach · 17:00',
    title: 'WEED BOXING 1', card: 'WHERE THE SERIES STARTED', fights: ['FIRST EDITION · ARCHIVE CARD'], source: 'https://t.me/kurnibratokk/5',
    image: 'https://cdn5.telesco.pe/file/ucQDBVZRQk5pvCzVZlQLrnDZ5UhDGeuCF09EayZM8HkEbgMAmfBflUt_iQ21wb6zbmWE8XAS2_ZdUz3he-9YarnVY9M3DVIFe0Mpd-oAjlLLkZIvajkQkMQ2jMUiJus-EtnM6hYp5UcpRWwdJI_8z5sO38mMKuUEZm_hPv5IDbgKbbSxLQKSWCy4qskyMjpDe4daQno0hWEJodlDzn4JC_Bql98xycCkD66kOCjI-TlHEbn1tOMD_aB2fv1vk4oA2HbuGWNVtXfa-aVmnqZaofSr4_wZLPeX9tGqEVDVWM1NeBjfaY3kXGhxUlQH73EZazg04fazeeXVHImsIUEr-A.jpg',
    gallery: [
      'https://cdn5.telesco.pe/file/Yr7TC9z6liBbwwIz4tlcW1rZjLEkq0GetIc5233WRfj6iN6CHtIrGyIM1AE3EQGo7Rkv0v565JuxTEwJFO1EglfElf3Wum-p6ogZKBV-qVwnZ8ffzqe5CfMimpcdWrcEuYlNltsog_nfkbbnFJ6LyBY-OashhNJ8Z9csRcmdycjIwDMN8sSPx602KRvfFnGcoTEAx2SNuoHhW6NzbbD0LdgnTlhVeGOv8kkXlcJ2ujW6O2WJtDs1sCG-hTUNKPFx9b1buFkLqdV672nBiAlpyA4cUQQXXXzfluPrXZ9nVeDXB3l-Ydb9eTbUcYbcU1hN3y_bEiA1xrEjqQAwCM7dqA.jpg',
      'https://cdn5.telesco.pe/file/Wle2aRIJN-nZlkGLO0NevyQgOqSwEvaLPUjbtZoltFvAk1YFyzeSbFtR1C37m_xkeWET8YoFu0h32fLCawOc9S-XtyseDQUljUvVe_VA0HXHIjR4p-n1PdQgVkISLbLtyVVQ7kDKcPdaNNyHLLicvLb7Xllo61PAcGc8-HZhl29KxgASoTsq91zNLyjZdW4VmA0UO-OSAq4brePqUYEqkY99NI1FqOCWH2ATAESKuHcc_i__e0TE95iHtxeBP_Gd5Po-iFfBsgPHSbm8pfM15Dsds0l-3evs1tA9L7sUA_qdNuci52cOd6PWRZ6m53tv9km16_LbwbKp8OXkTVTU2A.jpg',
    ],
  },
];

export const copy = {
  en: {
    nav: ['About', 'Events', 'Fighters', 'Merch'], apply: 'Apply to fight', eyebrow: 'Independent fight series · Thailand',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'Independent fight series from Thailand.',
    scroll: 'Explore the series', rounds: ['THE RITUAL', '3 ROUNDS', '3 MINUTES'],
    manifestoTag: 'About the project', manifesto: 'WEEDBOXING: A BOXING TOURNAMENT BORN IN THAILAND.',
    about: 'Weedboxing is an independent boxing tournament and fight entertainment project based in Thailand. The series brings together athletes from boxing, Muay Thai, MMA and other combat sports. A cannabis ritual takes place before the bell; every bout itself follows boxing rules. Events combine live fights, music, street art and the energy of Thailand’s independent scene.',
    formatTag: 'A different competition format', formatTitle: 'PUFF. FIGHT. CHILL.', formatSteps: ['The pre-fight ritual. Focus shifts and the atmosphere changes.', 'The bell separates ritual from sport. From here, only the bout matters.', 'After the decision, opponents return to the same community.'],
    watch: 'Official teaser', teaser: 'Official teaser · Thailand', next: 'Next event', announced: 'Updates coming soon', ticket: 'Follow updates', lineup: 'Fight card', cardTba: 'Date and card to be announced',
    archive: 'Past editions', archiveTitle: 'OUR EVENTS.', recap: 'Explore event', allEvents: 'All events',
    rankTag: 'Official fighter ranking', rankTitle: 'THE OFFICIAL RANKING.', rankSub: 'Updated after every event. Position reflects results, activity and strength of opposition.',
    fighter: 'Fighter', record: 'Record', weight: 'Weight', allFighters: 'Full ranking', champion: 'Ranking leader · No. 1', contenders: 'Ranked 2–3', topRanked: 'Top 10', nextRanked: 'Ranked 4–6', restRoster: 'The rest of the roster', viewProfile: 'Instagram',
    joinTag: 'Applications are open', joinTitle: 'STEP INTO THE SERIES.', joinText: 'We consider experienced athletes from boxing, Muay Thai, MMA and other combat disciplines. Send your record, weight and recent fight footage to our matchmaking team.', joinButton: 'Apply to fight',
    merchTag: 'Official merchandise', merchTitle: 'THE FIRST DROP IS IN DEVELOPMENT.', merchText: 'We are working on the cut, materials and graphics. The collection will be presented when the actual pieces are ready.', buy: 'Follow the release',
    investTag: 'Build the next chapter with us', investTitle: 'A FORMAT BUILT TO TRAVEL.', investText: 'We invite strategic partners, venues and investors to develop an international fight entertainment series rooted in Thailand.', investButton: 'Discuss partnership',
    partners: 'Friends of the project', footer: 'From Thailand. Built for a global audience.', rights: '© 2026 WEEDBOXING. ALL RIGHTS RESERVED.',
    pageEvents: 'OUR EVENTS.', pageEventsSub: 'Past editions from Koh Samui and Phuket. Open an event for the venue, card and photo archive.',
    pageFighters: 'FIGHTER RANKING.', pageFightersSub: 'Every athlete who entered the series. Records are updated after each event.',
    search: 'Search a fighter', filter: 'All weights', fights: 'Fights', wins: 'W', draws: 'D', losses: 'L', country: 'Country', profile: 'IG', eventBack: 'All events', eventAbout: 'About this edition', eventGallery: 'Event gallery', eventSource: 'Original announcement',
  },
  ru: {
    nav: ['О проекте', 'Ивенты', 'Бойцы', 'Мерч'], apply: 'Подать заявку', eyebrow: 'Независимая бойцовская серия · Таиланд',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'Независимая бойцовская серия из Таиланда.',
    scroll: 'Смотреть проект', rounds: ['РИТУАЛ', '3 РАУНДА', '3 МИНУТЫ'],
    manifestoTag: 'О проекте', manifesto: 'WEEDBOXING — БОКСЕРСКИЙ ТУРНИР, СОЗДАННЫЙ В ТАИЛАНДЕ.',
    about: 'Weedboxing — независимый боксерский турнир и проект в сфере бойцовских развлечений, базирующийся в Таиланде. Серия объединяет атлетов из бокса, муай-тай, MMA и других единоборств. Перед гонгом проходит каннабис-ритуал, а сами поединки проводятся по правилам бокса. В событиях соединяются живые бои, музыка, уличное искусство и энергия независимой сцены Таиланда.',
    formatTag: 'Другой формат соревнования', formatTitle: 'PUFF. FIGHT. CHILL.', formatSteps: ['Ритуал перед боем. Меняется фокус и атмосфера вокруг ринга.', 'Гонг отделяет ритуал от спорта. Дальше значение имеет только поединок.', 'После решения судей соперники снова становятся частью одного комьюнити.'],
    watch: 'Официальный тизер', teaser: 'Официальный тизер · Таиланд', next: 'Следующий ивент', announced: 'Анонс скоро', ticket: 'Следить за новостями', lineup: 'Кард', cardTba: 'Дата и состав будут объявлены',
    archive: 'Прошедшие выпуски', archiveTitle: 'НАШИ СОБЫТИЯ.', recap: 'Открыть событие', allEvents: 'Все ивенты',
    rankTag: 'Официальный рейтинг бойцов', rankTitle: 'ОФИЦИАЛЬНЫЙ РЕЙТИНГ.', rankSub: 'Обновляется после каждого события. Позиция учитывает результаты, активность и уровень соперников.',
    fighter: 'Боец', record: 'Рекорд', weight: 'Вес', allFighters: 'Весь рейтинг', champion: 'Лидер рейтинга · №1', contenders: 'Места 2–3', topRanked: 'Топ-10', nextRanked: 'Места 4–6', restRoster: 'Остальной ростер', viewProfile: 'Instagram',
    joinTag: 'Прием заявок открыт', joinTitle: 'СТАНЬ ЧАСТЬЮ СЕРИИ.', joinText: 'Мы рассматриваем опытных атлетов из бокса, муай-тай, MMA и других единоборств. Отправь матчмейкерам свой рекорд, вес и видео последних боев.', joinButton: 'Подать заявку',
    merchTag: 'Официальный мерч', merchTitle: 'ПЕРВЫЙ ДРОП В РАЗРАБОТКЕ.', merchText: 'Мы работаем над кроем, материалами и графикой. Коллекция будет представлена, когда реальные изделия будут готовы.', buy: 'Следить за релизом',
    investTag: 'Создадим следующую главу вместе', investTitle: 'ФОРМАТ, ГОТОВЫЙ К МАСШТАБУ.', investText: 'Приглашаем стратегических партнеров, площадки и инвесторов развивать международную серию бойцовских событий, созданную в Таиланде.', investButton: 'Обсудить партнерство',
    partners: 'Друзья проекта', footer: 'Создано в Таиланде. Для мировой аудитории.', rights: '© 2026 WEEDBOXING. ВСЕ ПРАВА ЗАЩИЩЕНЫ.',
    pageEvents: 'НАШИ СОБЫТИЯ.', pageEventsSub: 'Прошедшие выпуски на Самуи и Пхукете. Внутри каждого — площадка, кард и фотоархив.',
    pageFighters: 'РЕЙТИНГ БОЙЦОВ.', pageFightersSub: 'Все атлеты, выходившие в серии. Рекорды обновляются после каждого события.',
    search: 'Найти бойца', filter: 'Все веса', fights: 'Бои', wins: 'П', draws: 'Н', losses: 'Пор', country: 'Страна', profile: 'IG', eventBack: 'Все события', eventAbout: 'Об этом выпуске', eventGallery: 'Фотографии события', eventSource: 'Оригинальный анонс',
  },
  th: {
    nav: ['เกี่ยวกับเรา', 'อีเวนต์', 'นักสู้', 'สินค้า'], apply: 'สมัครชก', eyebrow: 'ซีรีส์การต่อสู้อิสระ · ประเทศไทย',
    heroA: 'WEED', heroB: 'BOXING', heroText: 'ซีรีส์การต่อสู้อิสระจากประเทศไทย',
    scroll: 'สำรวจโปรเจกต์', rounds: ['พิธี', '3 ยก', '3 นาที'],
    manifestoTag: 'เกี่ยวกับโปรเจกต์', manifesto: 'WEEDBOXING การแข่งขันมวยที่กำเนิดในประเทศไทย',
    about: 'Weedboxing คือการแข่งขันมวยอิสระและโปรเจกต์ความบันเทิงด้านการต่อสู้ในประเทศไทย ซีรีส์รวมนักกีฬาจากมวยสากล มวยไทย MMA และศิลปะการต่อสู้อื่นๆ มีพิธีกัญชาก่อนเสียงระฆัง ส่วนการแข่งขันดำเนินภายใต้กติกามวยสากล พร้อมดนตรี ศิลปะบนท้องถนน และพลังของชุมชนอิสระในประเทศไทย',
    formatTag: 'รูปแบบการแข่งขันที่แตกต่าง', formatTitle: 'PUFF. FIGHT. CHILL.', formatSteps: ['พิธีก่อนการต่อสู้ เปลี่ยนสมาธิและบรรยากาศรอบเวที', 'เสียงระฆังแยกพิธีออกจากกีฬา จากนั้นมีเพียงการแข่งขัน', 'หลังคำตัดสิน คู่ต่อสู้กลับมาเป็นส่วนหนึ่งของชุมชนเดียวกัน'],
    watch: 'ทีเซอร์อย่างเป็นทางการ', teaser: 'ทีเซอร์อย่างเป็นทางการ · ประเทศไทย', next: 'อีเวนต์ถัดไป', announced: 'ประกาศเร็วๆ นี้', ticket: 'ติดตามข่าวสาร', lineup: 'คู่ชก', cardTba: 'วันและคู่ชกจะประกาศภายหลัง',
    archive: 'อีเวนต์ที่ผ่านมา', archiveTitle: 'อีเวนต์ของเรา', recap: 'ดูอีเวนต์', allEvents: 'อีเวนต์ทั้งหมด',
    rankTag: 'อันดับนักสู้อย่างเป็นทางการ', rankTitle: 'อันดับอย่างเป็นทางการ', rankSub: 'อัปเดตหลังทุกอีเวนต์ โดยพิจารณาผลงาน ความต่อเนื่อง และระดับคู่ต่อสู้',
    fighter: 'นักสู้', record: 'สถิติ', weight: 'น้ำหนัก', allFighters: 'อันดับทั้งหมด', champion: 'ผู้นำอันดับ · №1', contenders: 'อันดับ 2–3', topRanked: '10 อันดับแรก', nextRanked: 'อันดับ 4–6', restRoster: 'นักสู้คนอื่น', viewProfile: 'Instagram',
    joinTag: 'เปิดรับสมัคร', joinTitle: 'เข้าร่วมซีรีส์', joinText: 'เรารับนักกีฬาที่มีประสบการณ์จากมวยสากล มวยไทย MMA และศิลปะการต่อสู้อื่นๆ ส่งสถิติ น้ำหนัก และวิดีโอการชกล่าสุดให้ทีมงาน', joinButton: 'สมัครชก',
    merchTag: 'สินค้าอย่างเป็นทางการ', merchTitle: 'คอลเลกชันแรกกำลังพัฒนา', merchText: 'เรากำลังพัฒนาทรง วัสดุ และกราฟิก คอลเลกชันจะเปิดตัวเมื่อสินค้าจริงพร้อม', buy: 'ติดตามการเปิดตัว',
    investTag: 'สร้างบทต่อไปด้วยกัน', investTitle: 'รูปแบบที่พร้อมเติบโตทั่วโลก', investText: 'เราเชิญพันธมิตร สถานที่ และนักลงทุน ร่วมพัฒนาซีรีส์การต่อสู้ระดับนานาชาติจากประเทศไทย', investButton: 'พูดคุยความร่วมมือ',
    partners: 'เพื่อนของโปรเจกต์', footer: 'สร้างในประเทศไทย เพื่อผู้ชมทั่วโลก', rights: '© 2026 WEEDBOXING. ALL RIGHTS RESERVED.',
    pageEvents: 'อีเวนต์ของเรา', pageEventsSub: 'อีเวนต์ที่ผ่านมาบนเกาะสมุยและภูเก็ต เปิดดูสถานที่ คู่ชก และคลังภาพ',
    pageFighters: 'อันดับนักสู้', pageFightersSub: 'นักกีฬาทุกคนที่เข้าร่วมซีรีส์ อัปเดตสถิติหลังทุกอีเวนต์',
    search: 'ค้นหานักสู้', filter: 'ทุกน้ำหนัก', fights: 'ไฟต์', wins: 'ช', draws: 'ส', losses: 'พ', country: 'ประเทศ', profile: 'IG', eventBack: 'อีเวนต์ทั้งหมด', eventAbout: 'เกี่ยวกับอีเวนต์', eventGallery: 'แกลเลอรี', eventSource: 'ประกาศต้นฉบับ',
  },
};
