export const fighters = [
  { rank: 1, name: 'NARKOTIK ATHLETIC', country: 'Russia', flag: 'RU', weight: '70', fights: 5, wins: 4, draws: 1, losses: 0, instagram: 'https://www.instagram.com/crystalhomewarrior' },
  { rank: 2, name: 'RUSLAN BROKER BRAKER', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 3, draws: 1, losses: 0, instagram: 'https://www.instagram.com/rus.lan.812' },
  { rank: 3, name: 'PASHOK PIVO', country: 'Russia', flag: 'RU', weight: '70', fights: 4, wins: 1, draws: 2, losses: 1, instagram: 'https://www.instagram.com/praga_tatulios' },
  { rank: 4, name: 'PITON', country: 'Russia', flag: 'RU', weight: '70-75', fights: 4, wins: 1, draws: 3, losses: 0, instagram: 'https://www.instagram.com/prvtya11' },
  { rank: 5, name: 'DICH', country: 'Russia', flag: 'RU', weight: '76', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dichnakolkin.comm' },
  { rank: 6, name: 'BRONSON', country: 'Ukraine', flag: 'UA', weight: '90+', fights: 2, wins: 2, draws: 0, losses: 0, instagram: 'https://www.instagram.com/mr.projar' },
  { rank: 7, name: 'RIZA', country: 'Turkey', flag: 'TR', weight: '70', fights: 5, wins: 1, draws: 2, losses: 2 },
  { rank: 8, name: 'VIKING', country: 'Russia', flag: 'RU', weight: '80', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/denisviking_ugc' },
  { rank: 9, name: 'OZAN', country: 'Turkey', flag: 'TR', weight: '85', fights: 2, wins: 1, draws: 1, losses: 0, instagram: 'https://www.instagram.com/ozanmma' },
  { rank: 10, name: 'ROSTOK BORSKI', country: 'Russia', flag: 'RU', weight: '75', fights: 2, wins: 1, draws: 0, losses: 1, instagram: 'https://www.instagram.com/ninocolot' },
  { rank: 11, name: 'VALENTIN VARYAG', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/valentin88varyag' },
  { rank: 12, name: 'MAKOR', country: 'Russia', flag: 'RU', weight: '70', fights: 2, wins: 0, draws: 1, losses: 1, instagram: 'https://www.instagram.com/alexmakorin88' },
  { rank: 13, name: 'AMIR', country: 'Russia', flag: 'RU', weight: '70', fights: 3, wins: 1, draws: 1, losses: 1, instagram: 'https://www.instagram.com/imanov_amir_' },
  { rank: 14, name: 'SHARE', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/share88' },
  { rank: 15, name: 'NIKITA RATIBOR', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/nikita_ratibor_firefighter' },
  { rank: 16, name: 'DIMA DD', country: 'Russia', flag: 'RU', weight: '80', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/9dima_dd' },
  { rank: 17, name: 'VICTOR BUTI', country: 'England', flag: 'GB', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 18, name: 'IVAN PARSHIKOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/victorkeifbooty' },
  { rank: 19, name: 'EDIK', country: 'Ukraine', flag: 'UA', weight: '75', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/demenko777' },
  { rank: 20, name: 'ONUR', country: 'Turkey', flag: 'TR', weight: '75', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/onurtekermma' },
  { rank: 21, name: 'THE BULL', country: 'USA', flag: 'US', weight: '85', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/gtacharlie_decca' },
  { rank: 22, name: 'SALAWAT', country: 'Uzbekistan', flag: 'UZ', weight: '90+', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/dzhabbarbergenovs' },
  { rank: 23, name: 'DAN ZIGER', country: 'Nigeria', flag: 'NG', weight: '85', fights: 2, wins: 1, draws: 0, losses: 1 },
  { rank: 24, name: 'BIRKIN F9EVIL', country: 'Ukraine', flag: 'UA', weight: '70', fights: 1, wins: 0, draws: 0, losses: 1, instagram: 'https://www.instagram.com/f9evil' },
  { rank: 25, name: 'POKOLENIE MIKROZAIMOV', country: 'Russia', flag: 'RU', weight: '70', fights: 1, wins: 1, draws: 0, losses: 0, instagram: 'https://www.instagram.com/pokoleniemikrozaymov' },
];

export const events = [
  {
    id: 'bangkok-09', status: 'upcoming', number: '09', date: '28 SEP 2026', city: 'BANGKOK', venue: 'Secret Warehouse · 21:00',
    title: 'SMOKE BREAK', card: 'NARKOTIK vs BRONSON',
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1600&q=85',
  },
  {
    id: 'phuket-08', status: 'past', number: '08', date: '19 APR 2026', city: 'PHUKET', venue: 'Rawai Arena',
    title: 'HIGH STAKES', card: 'VIKING vs OZAN',
    image: 'https://images.unsplash.com/photo-1564415315949-7a0c4c73aab4?auto=format&fit=crop&w=1200&q=85',
  },
  {
    id: 'pattaya-07', status: 'past', number: '07', date: '08 FEB 2026', city: 'PATTAYA', venue: 'Underground Club',
    title: 'NO BAD TRIPS', card: 'RUSLAN vs PITON',
    image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=1200&q=85',
  },
];

export const copy = {
  en: {
    nav: ['About', 'Events', 'Fighters', 'Merch'], apply: 'Get in the ring', eyebrow: 'Born in Thailand · Est. 2024',
    heroA: 'SMOKE', heroB: 'FIRST.', heroC: 'FIGHT', heroD: 'AFTER.', heroText: 'They take a hit. Then they take a hit.',
    scroll: 'Scroll into the smoke', rounds: ['1 JOINT', '3 ROUNDS', '3 MINUTES'],
    manifestoTag: 'The rules are different here', manifesto: 'ONE HIT OF SMOKE. NINE MINUTES TO PROVE YOURSELF.',
    about: 'Weedboxing is a raw fight show where cannabis culture meets the sweet science. Fighters smoke a joint or hit a bong before the bell. Then: three rounds, three minutes, zero excuses.',
    watch: 'Fight highlights', next: 'Next impact', announced: 'Fight night announced', ticket: 'Get fight pass', lineup: 'Main card',
    archive: 'Fight archive', archiveTitle: 'THE NIGHTS WE CAN BARELY REMEMBER.', recap: 'View recap', allEvents: 'All events',
    rankTag: 'Official smokeweight ranking', rankTitle: 'WHO RUNS THIS JOINT?', rankSub: 'Updated after every event. Ranked by wins, activity and ability to keep it together.',
    fighter: 'Fighter', record: 'Record', weight: 'Weight', allFighters: 'Full ranking', champion: 'Smokeweight champion', contenders: 'Next in line', topRanked: 'Top 10', restRoster: 'The rest of the roster', viewProfile: 'Open profile',
    joinTag: 'Think you can hang?', joinTitle: 'GET HIGH. GET WRAPPED. GET IN.', joinText: 'Pro, amateur, absolute lunatic: if you can fight and handle the ritual, send your tape. Our matchmakers are watching.', joinButton: 'Apply to fight',
    merchTag: 'Uniform for bad decisions', merchTitle: 'FIGHT CLUB SUPPLY', buy: 'Coming soon',
    investTag: 'This thing is growing', investTitle: 'BACK THE NEXT CULT SPORT.', investText: 'We are opening the ring to strategic partners, venues and investors ready to build a global fight entertainment brand from Thailand.', investButton: 'Talk business',
    partners: 'Partners in crime', footer: 'Smoke responsibly. Fight professionally.', rights: '© 2026 WEEDBOXING. ALL HITS RESERVED.',
    pageEvents: 'EVERY NIGHT. EVERY HIT.', pageEventsSub: 'Upcoming cards, full archive and stories from the smoke.',
    pageFighters: 'THE SMOKEWEIGHT TABLE.', pageFightersSub: 'Every fighter who stepped through our ropes. Records updated after fight night.',
    search: 'Search a fighter', filter: 'All weights', fights: 'Fights', wins: 'W', draws: 'D', losses: 'L', country: 'Country', profile: 'IG',
  },
  ru: {
    nav: ['О проекте', 'Ивенты', 'Бойцы', 'Мерч'], apply: 'Выйти на ринг', eyebrow: 'Рождено в Таиланде · С 2024',
    heroA: 'СНАЧАЛА', heroB: 'ДЫМ.', heroC: 'ПОТОМ', heroD: 'БОЙ.', heroText: 'Сначала они делают затяг. Потом принимают удар.',
    scroll: 'Ныряй в дым', rounds: ['1 КОСЯК', '3 РАУНДА', '3 МИНУТЫ'],
    manifestoTag: 'Здесь другие правила', manifesto: 'ОДНА ЗАТЯЖКА. ДЕВЯТЬ МИНУТ, ЧТОБЫ ДОКАЗАТЬ СВОЕ.',
    about: 'Weedboxing — дерзкое бойцовское шоу на стыке каннабис-культуры и классического бокса. Перед гонгом бойцы курят косяк или бонг. Дальше: три раунда, три минуты, никаких оправданий.',
    watch: 'Хайлайты боев', next: 'Следующий удар', announced: 'Новый ивент', ticket: 'Взять билет', lineup: 'Главный кард',
    archive: 'Архив боев', archiveTitle: 'НОЧИ, КОТОРЫЕ МЫ ЕЛЕ ПОМНИМ.', recap: 'Смотреть итоги', allEvents: 'Все ивенты',
    rankTag: 'Официальный smokeweight-рейтинг', rankTitle: 'КТО ЗДЕСЬ ГЛАВНЫЙ?', rankSub: 'Обновляется после каждого ивента. Победы, активность и умение держать себя в руках.',
    fighter: 'Боец', record: 'Рекорд', weight: 'Вес', allFighters: 'Весь рейтинг', champion: 'Smokeweight-чемпион', contenders: 'Дышат в спину', topRanked: 'Топ-10', restRoster: 'Остальной ростер', viewProfile: 'Открыть профиль',
    joinTag: 'Думаешь, вывезешь?', joinTitle: 'ЗАТЯНИСЬ. ЗАБИНТУЙСЯ. ВЫХОДИ.', joinText: 'Профи, любитель или абсолютный безумец: умеешь драться и готов к ритуалу — присылай видео. Матчмейкеры смотрят.', joinButton: 'Записаться на бой',
    merchTag: 'Форма для плохих решений', merchTitle: 'FIGHT CLUB SUPPLY', buy: 'Скоро в продаже',
    investTag: 'Проект набирает обороты', investTitle: 'ВЛОЖИСЬ В НОВЫЙ КУЛЬТОВЫЙ СПОРТ.', investText: 'Приглашаем стратегических партнеров, площадки и инвесторов построить международный бренд бойцовских шоу из Таиланда.', investButton: 'Обсудить сотрудничество',
    partners: 'Соучастники', footer: 'Кури ответственно. Дерись профессионально.', rights: '© 2026 WEEDBOXING. ВСЕ УДАРЫ ЗАЩИЩЕНЫ.',
    pageEvents: 'КАЖДАЯ НОЧЬ. КАЖДЫЙ УДАР.', pageEventsSub: 'Будущие карды, полный архив и истории из дыма.',
    pageFighters: 'SMOKEWEIGHT-РЕЙТИНГ.', pageFightersSub: 'Каждый, кто прошел между канатов. Рекорды обновляются после ивентов.',
    search: 'Найти бойца', filter: 'Все веса', fights: 'Бои', wins: 'П', draws: 'Н', losses: 'Пор', country: 'Страна', profile: 'IG',
  },
  th: {
    nav: ['เกี่ยวกับเรา', 'อีเวนต์', 'นักสู้', 'สินค้า'], apply: 'ขึ้นสังเวียน', eyebrow: 'กำเนิดในประเทศไทย · 2024',
    heroA: 'สูบ', heroB: 'ก่อน', heroC: 'ชก', heroD: 'ทีหลัง', heroText: 'สูดหนึ่งครั้ง แล้วรับหมัดหนึ่งที',
    scroll: 'เข้าสู่ควัน', rounds: ['1 มวน', '3 ยก', '3 นาที'],
    manifestoTag: 'กติกาที่ไม่เหมือนใคร', manifesto: 'หนึ่งควัน เก้านาที เพื่อพิสูจน์ตัวเอง',
    about: 'Weedboxing คือไฟต์โชว์ดิบที่ผสมวัฒนธรรมกัญชาเข้ากับศาสตร์แห่งมวย นักสู้สูบก่อนระฆังดัง จากนั้นสามยก ยกละสามนาที ไม่มีข้อแก้ตัว',
    watch: 'ไฮไลต์การชก', next: 'ไฟต์ถัดไป', announced: 'ประกาศไฟต์ไนท์', ticket: 'ซื้อบัตร', lineup: 'คู่เอก',
    archive: 'คลังไฟต์', archiveTitle: 'ค่ำคืนที่เราแทบจำไม่ได้', recap: 'ดูสรุป', allEvents: 'อีเวนต์ทั้งหมด',
    rankTag: 'อันดับ Smokeweight อย่างเป็นทางการ', rankTitle: 'ใครคุมที่นี่?', rankSub: 'อัปเดตหลังทุกอีเวนต์ จัดอันดับจากชัยชนะและผลงาน',
    fighter: 'นักสู้', record: 'สถิติ', weight: 'น้ำหนัก', allFighters: 'อันดับทั้งหมด', champion: 'แชมป์ Smokeweight', contenders: 'ผู้ท้าชิง', topRanked: '10 อันดับแรก', restRoster: 'นักสู้คนอื่น', viewProfile: 'เปิดโปรไฟล์',
    joinTag: 'คิดว่าไหวไหม?', joinTitle: 'สูบ พันมือ ขึ้นชก', joinText: 'มืออาชีพ มือสมัครเล่น หรือคนบ้าสุดขีด ถ้าคุณชกได้ ส่งวิดีโอมา ทีมงานกำลังดูอยู่', joinButton: 'สมัครขึ้นชก',
    merchTag: 'ชุดสำหรับการตัดสินใจสุดบ้า', merchTitle: 'FIGHT CLUB SUPPLY', buy: 'เร็วๆ นี้',
    investTag: 'เรากำลังเติบโต', investTitle: 'ร่วมสร้างกีฬาลัทธิยุคใหม่', investText: 'เราเชิญพันธมิตร สถานที่ และนักลงทุน ร่วมสร้างแบรนด์ไฟต์ระดับโลกจากประเทศไทย', investButton: 'คุยธุรกิจ',
    partners: 'พันธมิตร', footer: 'สูบอย่างรับผิดชอบ ชกอย่างมืออาชีพ', rights: '© 2026 WEEDBOXING. ALL HITS RESERVED.',
    pageEvents: 'ทุกค่ำคืน ทุกหมัด', pageEventsSub: 'ไฟต์ที่กำลังจะมา คลังทั้งหมด และเรื่องราวในควัน',
    pageFighters: 'ตาราง SMOKEWEIGHT', pageFightersSub: 'นักสู้ทุกคนที่ขึ้นสังเวียน อัปเดตสถิติหลังไฟต์ไนท์',
    search: 'ค้นหานักสู้', filter: 'ทุกน้ำหนัก', fights: 'ไฟต์', wins: 'ช', draws: 'ส', losses: 'พ', country: 'ประเทศ', profile: 'IG',
  },
};
